import './style.css';

const IG='https://www.instagram.com/infiniti_games0125/';
const phone='923324681905';
const wa=(item='the available gaming products')=>`https://wa.me/${phone}?text=${encodeURIComponent(`Hi Infiniti Games, I found your website concept and would like to ask about ${item}. Is it available?`)}`;
const icon={arrow:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>',diag:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 19 19 5M8 5h11v11"/></svg>',menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 7h18M3 12h18M3 17h18"/></svg>',close:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 5 19 19M19 5 5 19"/></svg>',instagram:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="2.5" y="2.5" width="19" height="19" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.6" cy="6.6" r="1" fill="currentColor" stroke="none"/></svg>',whatsapp:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 11.8a8 8 0 0 1-11.6 7.1L3 20l1.2-5.1A8 8 0 1 1 20 11.8Z"/><path d="M8.6 8.4c.8 3 2.1 4.4 5.2 6 .8.3 1.5-.4 2-1.1"/></svg>'};
const photo=id=>`/images/ig-${id}-1.jpg`;
const products=[
 {title:'PlayStation 5',type:'Consoles',eyebrow:'THE MAIN EVENT',image:photo('C035K7zNS3-'),link:'https://www.instagram.com/p/C035K7zNS3-/',sub:'Console · games · controllers'},
 {title:'Inside the store',type:'The Shop',eyebrow:'THE REAL DEAL',image:photo('C7HDoQ4Ni4z'),link:'https://www.instagram.com/p/C7HDoQ4Ni4z/',sub:'Browse the shelves in Lahore'},
 {title:'Console picks',type:'Consoles',eyebrow:'LEVEL UP',image:photo('DYEUUeZMIAR'),link:'https://www.instagram.com/reel/DYEUUeZMIAR/',sub:'Ask about the latest arrivals'},
 {title:'Controller culture',type:'Accessories',eyebrow:'YOUR PLAYER TWO',image:'/images/ig-DXTgTFeDO4i-2.jpg',link:'https://www.instagram.com/reel/DXTgTFeDO4i/',sub:'Gear for the whole setup'},
 {title:'The next play',type:'Games',eyebrow:'PICK YOUR GAME',image:photo('DCorF1DNk-X'),link:'https://www.instagram.com/reel/DCorF1DNk-X/',sub:'Ask what is on the shelf'},
 {title:'More from Infiniti',type:'The Shop',eyebrow:'AT THE COUNTER',image:photo('DY_mp5VM0F4'),link:'https://www.instagram.com/reel/DY_mp5VM0F4/',sub:'Follow the shop in action'}
];

document.querySelector('#app').innerHTML=`
<div class="intro" id="intro" aria-hidden="true"><div class="intro-inner"><span class="intro-kicker">PLAYER ONE, READY?</span><img class="intro-logo" src="/images/infiniti-mark.jpg" alt=""/><strong>INFINITI<span>GAMES</span></strong><div class="intro-line"><i></i></div><span class="intro-small">LOADING THE NEXT LEVEL</span></div><button class="intro-skip" id="skipIntro">SKIP INTRO ${icon.arrow}</button></div>
<div class="site-shell">
 <div class="topline"><span>LAHORE, PAKISTAN / PIA MAIN BOULEVARD</span><span>NEW & USED CONSOLES · GAMES · ACCESSORIES</span><a href="${IG}" target="_blank" rel="noopener">FOLLOW THE ACTION ${icon.diag}</a></div>
 <header class="header" id="header"><a href="#top" class="brand" aria-label="Infiniti Games home"><img class="brand-logo" src="/images/infiniti-mark.jpg" alt=""/><span class="brand-words">INFINITI <b>GAMES</b><small>LAHORE · PAKISTAN</small></span></a><nav class="desktop-nav" aria-label="Main navigation"><a href="#collection">THE COLLECTION</a><a href="#experience">THE EXPERIENCE</a><a href="#social">FROM THE SHOP</a><a href="#visit">VISIT US</a></nav><a class="nav-cta" href="${wa()}" target="_blank" rel="noopener">ASK WHAT'S IN STOCK ${icon.diag}</a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false">${icon.menu}</button></header>
 <div class="mobile-menu" id="mobileMenu"><a href="#collection">THE COLLECTION</a><a href="#experience">THE EXPERIENCE</a><a href="#social">FROM THE SHOP</a><a href="#visit">VISIT US</a><a href="${wa()}" target="_blank" rel="noopener">ASK ON WHATSAPP ${icon.diag}</a></div>
 <main id="top">
  <section class="hero" aria-labelledby="heroTitle"><div class="hero-grid"></div><div class="hero-orb"></div><div class="hero-content"><div class="hero-top"><span class="eyebrow"><i></i> LAHORE'S GAME CULTURE, UP CLOSE</span><span class="hero-index">01 / 04 — THE WORLD OF INFINITI</span></div><div class="hero-heading"><span class="hero-title-small">YOUR NEXT</span><h1 id="heroTitle">GAME<br><em>STARTS</em><br>HERE<span class="punct">.</span></h1><p>From the console you’ve been chasing to the game you can’t put down. Find your next obsession at Infiniti Games.</p><div class="hero-actions"><a class="btn-primary" href="#collection">EXPLORE THE COLLECTION ${icon.arrow}</a><a class="text-link" href="${wa()}" target="_blank" rel="noopener">TALK TO THE TEAM ${icon.diag}</a></div></div><div class="hero-bottom"><span>SCROLL TO EXPLORE <i>↓</i></span><span>CONSOLE CULTURE / SINCE DAY ONE</span></div></div><div class="hero-visual"><div class="hero-image-frame"><img src="${photo('C035K7zNS3-')}" alt="PlayStation 5 console, game and controllers photographed by Infiniti Games" fetchpriority="high"/><span class="image-stamp">SEEN AT INFINITI / 001</span></div><div class="hero-vertical">REAL GEAR. REAL PEOPLE. REAL PLAY.</div><div class="visual-number">01<span>/04</span></div></div></section>
  <div class="marquee" aria-label="Consoles, games, accessories and more"><div class="marquee-track" aria-hidden="true">CONSOLES <span>✳</span> GAMES <span>✳</span> ACCESSORIES <span>✳</span> YOUR NEXT LEVEL <span>✳</span> CONSOLES <span>✳</span> GAMES <span>✳</span> ACCESSORIES <span>✳</span> YOUR NEXT LEVEL <span>✳</span></div></div>
  <section class="section collection" id="collection"><div class="section-head reveal"><div><span class="label">01 / THE COLLECTION</span><h2>THE GOOD<br><em>STUFF.</em></h2></div><div class="section-aside"><p>A glimpse of the consoles, games and gear featured by Infiniti Games. Stock and prices move fast—ask the team for what’s available today.</p><a href="${IG}" target="_blank" rel="noopener">SEE THEIR INSTAGRAM ${icon.diag}</a></div></div><div class="filter-row reveal" role="group" aria-label="Filter collection"><button class="filter active" data-filter="All" aria-pressed="true">ALL <span>06</span></button><button class="filter" data-filter="Consoles" aria-pressed="false">CONSOLES</button><button class="filter" data-filter="Games" aria-pressed="false">GAMES</button><button class="filter" data-filter="Accessories" aria-pressed="false">ACCESSORIES</button><button class="filter" data-filter="The Shop" aria-pressed="false">THE SHOP</button></div><div class="product-grid" id="productGrid"></div><div class="collection-foot reveal"><span>THE RIGHT GEAR CHANGES EVERYTHING.</span><a class="circle-link" href="${wa()}" target="_blank" rel="noopener" aria-label="Ask Infiniti Games about available products">${icon.diag}</a></div></section>
  <section class="story" id="experience"><div class="story-image"><img src="${photo('C7HDoQ4Ni4z')}" loading="lazy" alt="A look inside Infiniti Games' store from their Instagram"/><span>THE STORE / PIA MAIN BOULEVARD</span></div><div class="story-copy"><span class="label">02 / BEYOND THE SCREEN</span><h2>BUILT FOR<br>PEOPLE WHO<br><em>PLAY.</em></h2><p>There’s something different about finding your next console in a shop that actually lives and breathes games. Browse, ask questions, get a feel for the gear, and leave ready for your next session.</p><div class="story-details"><div><strong>01</strong><span>CONSOLES & GEAR</span></div><div><strong>02</strong><span>GAMES TO DISCOVER</span></div><div><strong>03</strong><span>THE HUMAN TOUCH</span></div></div><a class="btn-outline" href="${wa('visiting the store and current stock')}" target="_blank" rel="noopener">LET'S TALK GAMES ${icon.arrow}</a></div></section>
  <section class="feature"><span class="label">03 / YOUR NEXT MOVE</span><div class="feature-main"><div><h2>FIND IT.<br>PLAY IT.<br><em>LIVE IT.</em></h2></div><div class="feature-right"><p>From your first console to the next addition to your setup, the best place to start is a conversation. Tell the team what you're looking for.</p><a class="feature-link" href="${wa('a console, game or accessory')}" target="_blank" rel="noopener"><span>MESSAGE INFINITI GAMES</span><span class="feature-arrow">${icon.diag}</span></a></div></div><div class="feature-deco" aria-hidden="true">∞</div></section>
  <section class="section social" id="social"><div class="section-head reveal"><div><span class="label">04 / FROM THE SHOP FLOOR</span><h2>THE FEED<br><em>IS LIVE.</em></h2></div><div class="section-aside"><p>Real moments from their Instagram. Follow Infiniti Games for new arrivals, shop updates and all things gaming.</p><a href="${IG}" target="_blank" rel="noopener">@INFINITI_GAMES0125 ${icon.diag}</a></div></div><div class="social-grid" id="socialGrid"></div></section>
  <section class="visit" id="visit"><div class="visit-inner"><span class="label">05 / PULL UP</span><h2>THE GAME<br>IS <em>WAITING.</em></h2><div class="visit-line"><div><span>FIND THE SHOP</span><strong>PIA MAIN BOULEVARD<br>LAHORE, PAKISTAN</strong></div><div><span>OPENING HOURS</span><strong>TUE — SUN / 1:00 PM — 9:00 PM<br>MONDAY / CLOSED</strong></div><div><span>GET IN TOUCH</span><strong>+92 332 4681905<br>@INFINITI_GAMES0125</strong></div></div><a class="btn-primary visit-button" href="${wa('visiting Infiniti Games')}" target="_blank" rel="noopener">ASK THE TEAM ${icon.arrow}</a></div><div class="visit-watermark" aria-hidden="true">INFINITI</div></section>
 </main><footer><div class="footer-top"><a href="#top" class="brand"><img class="brand-logo" src="/images/infiniti-mark.jpg" alt=""/><span class="brand-words">INFINITI <b>GAMES</b><small>LAHORE · PAKISTAN</small></span></a><div><a href="#collection">COLLECTION</a><a href="#experience">ABOUT</a><a href="${IG}" target="_blank" rel="noopener">INSTAGRAM ${icon.diag}</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} INFINITI GAMES · CONCEPT EXPERIENCE</span><span>AN UNOFFICIAL SALES CONCEPT BY <a href="https://h2svolt.com" target="_blank" rel="noopener">H2S VOLT</a> · PRODUCT AVAILABILITY & PRICES ARE CONFIRMED BY THE SHOP.</span><a href="#top">BACK TO TOP ↑</a></div></footer>
 <a class="floating-wa" href="${wa()}" target="_blank" rel="noopener" aria-label="Message Infiniti Games on WhatsApp">${icon.whatsapp}<span>ASK THE TEAM</span></a>
</div>`;

const card=(p,i)=>`<article class="product-card reveal" data-type="${p.type}"><div class="product-photo"><img src="${p.image}" loading="lazy" alt="${p.title} featured in Instagram content by Infiniti Games" onerror="this.src='/images/ig-C035K7zNS3--1.jpg'"/><div class="photo-label">${p.eyebrow}</div><a class="image-out" href="${p.link}" target="_blank" rel="noopener" aria-label="View original Instagram post for ${p.title}">${icon.diag}</a></div><div class="product-meta"><span>${String(i+1).padStart(2,'0')} / ${p.type.toUpperCase()}</span><span>ASK FOR AVAILABILITY</span></div><div class="product-title"><div><h3>${p.title}</h3><p>${p.sub}</p></div><a href="${wa(p.title)}" target="_blank" rel="noopener" aria-label="Enquire about ${p.title}">${icon.arrow}</a></div></article>`;
document.querySelector('#productGrid').innerHTML=products.map(card).join('');
document.querySelector('#socialGrid').innerHTML=[products[1],products[0],products[5],products[3]].map((p,i)=>`<a class="social-item reveal" href="${p.link}" target="_blank" rel="noopener" aria-label="View Infiniti Games Instagram post: ${p.title}"><img src="${p.image}" loading="lazy" alt="${p.title} photo from Instagram" onerror="this.src='/images/ig-C035K7zNS3--1.jpg'"/><span class="social-overlay">${icon.instagram}<span>VIEW POST ${icon.diag}</span></span><span class="social-n">0${i+1}</span></a>`).join('');

document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn))});document.querySelectorAll('.product-card').forEach(c=>{c.hidden=btn.dataset.filter!=='All'&&c.dataset.type!==btn.dataset.filter})}));
const menuBtn=document.querySelector('.menu-toggle'),menu=document.querySelector('#mobileMenu');menuBtn.addEventListener('click',()=>{const open=!menu.classList.contains('open');menu.classList.toggle('open',open);menuBtn.setAttribute('aria-expanded',String(open));menuBtn.setAttribute('aria-label',open?'Close menu':'Open menu');menuBtn.innerHTML=open?icon.close:icon.menu});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');menuBtn.setAttribute('aria-label','Open menu');menuBtn.innerHTML=icon.menu}));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const intro=document.querySelector('#intro');const finish=()=>{intro.classList.add('done');setTimeout(()=>intro.remove(),750)};document.querySelector('#skipIntro').addEventListener('click',finish);setTimeout(finish,reduced?100:2100);
if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px 40px 0px'});document.querySelectorAll('.reveal,.story-copy,.story-image,.feature-main').forEach(el=>io.observe(el))}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));
window.addEventListener('scroll',()=>document.querySelector('#header').classList.toggle('scrolled',scrollY>60),{passive:true});
